# Generated by Django 5.0.6 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=155)),
                ('number', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='book_table',
        ),
    ]
