# Generated by Django 5.0.6 on 2024-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeap', '0002_booktable_delete_book_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
